//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by es.cheah at ENGSOON on 11/10/2016 09:39:53 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace TR.Entities
{
    /// <summary>
    /// Represents a row of User data.
    /// </summary>
    [DataContract]
    public partial class Users
    {
        /// <summary>
        /// Gets or sets a long value for the UserID column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public long UserID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserName column.
        /// </summary>
        [DataMember]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Password column.
        /// </summary>
        [DataMember]
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Domain column.
        /// </summary>
        [DataMember]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the LastLogin column.
        /// </summary>
        [DataMember]
        public DateTime LastLogin { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the LastFailedLogin column.
        /// </summary>
        [DataMember]
        public DateTime LastFailedLogin { get; set; }

        /// <summary>
        /// Gets or sets a int value for the FailedAttempts column.
        /// </summary>
        [DataMember]
        public int FailedAttempts { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the Status column.
        /// </summary>
        [DataMember]
        public byte Status { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ChangePassword column.
        /// </summary>
        [DataMember]
        public bool ChangePassword { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateCreated column.
        /// </summary>
        [DataMember]
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateModified column.
        /// </summary>
        [DataMember]
        public DateTime DateModified { get; set; }
    }
}
