//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by es.cheah at ENGSOON on 11/10/2016 09:39:53 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace TR.Entities
{
    /// <summary>
    /// Represents a row of TrainingRequest data.
    /// </summary>
    [DataContract]
    public partial class TrainingRequest
    {
        /// <summary>
        /// Gets or sets a string value for the TRequestID column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public string TRequestID { get; set; }

        /// <summary>
        /// Gets or sets a Guid value for the CorrelationID column.
        /// </summary>
        [DataMember]
        public Guid CorrelationID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserName column.
        /// </summary>
        [DataMember]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the StartDate column.
        /// </summary>
        [DataMember]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EndDate column.
        /// </summary>
        [DataMember]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the RequestStatus column.
        /// </summary>
        [DataMember]
        public string RequestStatus { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the SubmitDate column.
        /// </summary>
        [DataMember]
        public DateTime SubmitDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the TrainingName column.
        /// </summary>
        [DataMember]
        public string TrainingName { get; set; }
    }
}
