//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by es.cheah at ENGSOON on 11/10/2016 09:39:53 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace TR.Entities
{
    /// <summary>
    /// Represents a row of UserLog data.
    /// </summary>
    [DataContract]
    public partial class UserLog
    {
        /// <summary>
        /// Gets or sets a string value for the UserLogID column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public string UserLogID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the TRequestID column.
        /// </summary>
        [DataMember]
        public string TRequestID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the RequestStatus column.
        /// </summary>
        [DataMember]
        public string RequestStatus { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the SubmitDate column.
        /// </summary>
        [DataMember]
        public DateTime SubmitDate { get; set; }
    }
}
