//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR.UI.Process.TrainingServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrainingServiceReference1.ITrainingService")]
    public interface ITrainingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/GetTraining", ReplyAction="http://tempuri.org/ITrainingService/GetTrainingResponse")]
        TR.Entities.TrainingRequest GetTraining(string tRequestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/GetTraining", ReplyAction="http://tempuri.org/ITrainingService/GetTrainingResponse")]
        System.Threading.Tasks.Task<TR.Entities.TrainingRequest> GetTrainingAsync(string tRequestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/ListTraining", ReplyAction="http://tempuri.org/ITrainingService/ListTrainingResponse")]
        System.Collections.Generic.List<TR.Entities.TrainingRequest> ListTraining(int currentPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/ListTraining", ReplyAction="http://tempuri.org/ITrainingService/ListTrainingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TR.Entities.TrainingRequest>> ListTrainingAsync(int currentPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/LoginVerify", ReplyAction="http://tempuri.org/ITrainingService/LoginVerifyResponse")]
        MK.Framework.ACE.Entities.User LoginVerify(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainingService/LoginVerify", ReplyAction="http://tempuri.org/ITrainingService/LoginVerifyResponse")]
        System.Threading.Tasks.Task<MK.Framework.ACE.Entities.User> LoginVerifyAsync(string Username, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainingServiceChannel : TR.UI.Process.TrainingServiceReference1.ITrainingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainingServiceClient : System.ServiceModel.ClientBase<TR.UI.Process.TrainingServiceReference1.ITrainingService>, TR.UI.Process.TrainingServiceReference1.ITrainingService {
        
        public TrainingServiceClient() {
        }
        
        public TrainingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TR.Entities.TrainingRequest GetTraining(string tRequestID) {
            return base.Channel.GetTraining(tRequestID);
        }
        
        public System.Threading.Tasks.Task<TR.Entities.TrainingRequest> GetTrainingAsync(string tRequestID) {
            return base.Channel.GetTrainingAsync(tRequestID);
        }
        
        public System.Collections.Generic.List<TR.Entities.TrainingRequest> ListTraining(int currentPage) {
            return base.Channel.ListTraining(currentPage);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TR.Entities.TrainingRequest>> ListTrainingAsync(int currentPage) {
            return base.Channel.ListTrainingAsync(currentPage);
        }
        
        public MK.Framework.ACE.Entities.User LoginVerify(string Username, string Password) {
            return base.Channel.LoginVerify(Username, Password);
        }
        
        public System.Threading.Tasks.Task<MK.Framework.ACE.Entities.User> LoginVerifyAsync(string Username, string Password) {
            return base.Channel.LoginVerifyAsync(Username, Password);
        }
    }
}
