//====================================================================================================
// Base code generated with Vector: WFA Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by es.cheah at ENGSOON on 11/09/2016 14:34:43 
//====================================================================================================

using System;
using System.Activities;
using System.Activities.Presentation.Metadata;
using System.ComponentModel;
using System.Windows;
using System.Collections.Generic;
using TR.Entities;
using TR.Workflows.Activities;

namespace TR.Workflows.Designers
{
    /// <summary>
    /// Designer class for Approve.
    /// </summary>
    public partial class ApproveDesigner : IRegisterMetadata
    {
        public ApproveDesigner()
        {
            InitializeComponent();
        }

        public void Register()
        {
            AttributeTableBuilder builder = new AttributeTableBuilder();

            builder.AddCustomAttributes(typeof(Approve), new Attribute[] {
            new DesignerAttribute(typeof(ApproveDesigner))});

            MetadataStore.AddAttributeTable(builder.CreateTable());
        }

        public void trainingRequestEntry_Loaded(object sender, RoutedEventArgs e)
        {
            trainingRequestEntry.ExpressionType = typeof(TrainingRequest);
        }

    }
}

