//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 3.0.5701.25371)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by es.cheah at ENGSOON on 11/07/2016 23:58:29 
//====================================================================================================

using MK.Framework.ACE.Entities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ServiceModel;
using TR.Entities;

namespace TR.Services.Contracts
{
    /// <summary>
    /// Service contract for TrainingService.
    /// </summary>
    [ServiceContract]
    public interface ITrainingService
    {
        [OperationContract]
        TrainingRequest GetTraining(string tRequestID);

        [OperationContract]
        List<TrainingRequest> ListTraining(int currentPage);

        [OperationContract]
        User LoginVerify(string Username, string Password);

        [OperationContract]
        void Export();

        [OperationContract]
        void Delay(TrainingRequest trainingRequest);


        [OperationContract]
        AccessPolicy GetUserPermission(long userID, string policyId);
    }
}
